# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d482baf2adb60fd618197f9462f2da8015ad0f5dc82b52ebc01507af246863f1828bd0fce2dfcd3e0b4e704a1668c5c28255f8c549385b47b7a54329ec2b78ed

test:
  secret_key_base: 225a671f992f0bc2c21ec58749d4c74eb06ccb04230a2cfd43b11a6ea57d0f4242fe19ad07380e36e7475fa26fe88b6715fc6a0147173e51a826ebaa7a200cf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
